---
- name: Configure Elk VM with Docker
  hosts: elk
  remote_user: sysadmin
  become: true
  tasks:
  # Use apt module
  - name: Install docker.io
    apt:
      force_apt_get: yes
      update_cache: yes
      name: docker.io
      state: present
  # Use apt module
  - name: Install pip3
    apt:
      force_apt_get: yes
     name: python3-pip
     state: present
  # Use pip module
  - name: Install Docker python module
     pip:
       name: docker
       state: present
  # Use command module
  - name: Increase virtual memory
    sysctl:
      name: vm.max_map_count
      value: '262144'
      state: present
      reload: yes
  # Use shell module
   - name: Increase virtual memory on restart
     shell: echo "vm.max_map_count=262144" >> /etc/sysctl.conf
  # Use docker_container module
  - name: download and launch a docker elk container
    docker_container:
    name: elk
    image: sebp/elk:740
    state: started
    restart_policy: always
    published_ports:
    - 5601:5601
    - 9200:9200
    - 5044:5044
  # This will automatically restart Docker Services
  - name: Enable docker service
    systemd:
      name: docker
      enabled: yes
